config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  resources :form_submissions, only: [:create, :show]

  resources :forms do
    resources :form_submissions, only: :index

    member do
      patch :publish
      get :view
    end
  end

  get 'error', to: 'pages#error'
  root 'forms#index'
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  before_action :http_basic_authenticate, except: :view
  before_action :set_form, only: [:show, :edit, :update, :publish, :view, :destroy]

  def index
    @forms = Form.select('forms.*, COUNT(form_submissions.id) AS form_submissions_count')
                 .left_outer_joins(:form_submissions).group('forms.id').order(created_at: :desc)
  end

  def new
    @form = Form.new
    @form.build_minimum_form_field
    @form_fields = @form.form_fields
  end

  def create
    @form = Form.new(form_params)
    if @form.save
      redirect_to @form, notice: 'Your form was created successfully'
    else
      @form.build_minimum_form_field
      @form_fields = @form.form_fields
      render :new
    end
  end

  def show
    @form_fields = @form.form_fields.includes(:form_field_options)
                        .order(:created_at).decorate
  end

  def edit
    @form_fields = @form.form_fields.order(:created_at)
  end

  def update
    if @form.update(form_params)
      redirect_to @form, notice: 'Your form was updated successfully'
    else
      @form.build_minimum_form_field
      # Do not reload form fields from the db (e.g. @form.form_fields.order(:created_at));
      # otherwise new form field options that have validation error will be wiped out and
      # user won't be able to see their error message
      #
      # Also need to divide the form fields into persisted and new records because the new records
      # don't have created_at yet so it can be sorted on that attribute. And we need to sort the
      # persisted records by created_at to preserve the form fields order
      @form_fields = @form.form_fields.persisted.sort_by(&:created_at) | @form.form_fields.new_record
      render :edit
    end
  end

  def publish
    if @form.published!
      redirect_to @form, notice: 'Your form was published successfully!'
    else
      render :show
    end
  end

  # For other users to view and submit the form
  def view
    unless params[:token] == @form.token
      redirect_to error_url, alert: t('errors.forbidden') and return
    end

    @form_submission = @form.build_form_submission
    @form_entries    = @form_submission.form_entries
  end

  def destroy
    @form.destroy
    redirect_to forms_url, notice: 'Your form was deleted successfully'
  end

  private

  def set_form
    @form = Form.find(params[:id])
  end

  def form_params
    params.require(:form).permit(
      :title,
      :description,
      form_fields_attributes: [:_destroy,
                               :id,
                               :name,
                               :description,
                               :type,
                               :required,
                               form_field_options_attributes: [:_destroy,
                                                               :id,
                                                               :value]]
    )
  end
end

app/helpers/forms_helper.rb
module FormsHelper
  def edit_form_link(form)
    return nil if form.published?
    link_to 'Edit', edit_form_path(form)
  end

  def publish_form_link(form)
    return nil unless form.in_progress?
    link_to 'Publish', publish_form_path(form),
            method: :patch,
            data:   { confirm: t('activerecord.confirmation.form.publish') }
  end

  def view_form_submissions_link(form)
    form_submissions_count = form.form_submissions.count
    return nil unless form.published? && form_submissions_count > 0
    link_to "View submissions (#{form_submissions_count})", form_form_submissions_path(form)
  end

  def form_entry_value_input(form_entry, form_entry_fields)
    input_hash = { label: false, as: form_field_type_2_sf_type(form_entry.form_field) }
    input_hash.merge!(
      if form_entry.form_field.has_options?
        { collection:    form_entry.form_field.form_field_options.pluck(:value),
          include_blank: !form_entry.form_field.required }
      else
        { input_html: { size: 50, rows: 7, cols: 50 } }
      end
    )

    form_entry_fields.input :value, input_hash
  end

  # Map the form field types to simple_form input types
  def form_field_type_2_sf_type(form_field)
    case
      when form_field.text?
        :string
      when form_field.textarea?
        :text
      when form_field.radio?
        :radio_buttons
      when form_field.checkbox?
        :check_boxes
      when form_field.drop_down?
        :select
    end
  end
end

app/views/forms/_form.html.erb
<%= simple_form_for(@form) do |f| %>
  <%= f.error_notification %>
  <% if f.object.errors[:base].present? %>
    <% f.object.errors[:base].each do |error_msg| %>
      <%= f.error_notification message: error_msg %>
    <% end %>
  <% end %>

  <div id="form-inputs-container" class="form-inputs">
    <%= field_set_tag do %>
      <%= f.input :title, autofocus: true, input_html: { size: 50, maxlength: 50 } %>
      <%= f.input :description, input_html: { size: 100, maxlength: 100 } %>
    <% end %>
    <% if @form_fields&.any? %>
      <%= content_tag :div, id: 'form-fields-container' do %>
        <% @form_fields.each do |form_field| %>
          <%= f.simple_fields_for :form_fields, form_field do |form_field_fields| %>
            <%= render 'form_field_fields', f: form_field_fields %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'Add field', f, :form_fields %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>&nbsp;&nbsp;
    <% if @form.persisted? %>
      <%= link_to 'Cancel', @form %>
    <% else %>
      <%= link_to 'Cancel', forms_path %>
    <% end %>
  </div>
<% end %>

app/views/forms/_form_field_fields.erb
<fieldset class="nested-fields">
  <%= f.input :name, input_html: { size: 50, maxlength: 50 } %>
  <%= f.input :description, input_html: { size: 100, maxlength: 100 } %>
  <%= f.input :type, collection: FormFieldDecorator.type_collection, include_blank: false %>
  <%= content_tag :div, id: 'form-field-options-container', class: 'form_field_option__container' do %>
    <%= content_tag :div, class: 'form-field-options-list' do %>
      <%= f.simple_fields_for :form_field_options do |form_field_option_fields| %>
        <%= render 'form_field_option_fields', f: form_field_option_fields %>
      <% end %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'Add option', f, :form_field_options %>
    </div>
  <% end %>
  <%= f.input :required %>
  <%= link_to_remove_association 'Remove field', f %>
</fieldset>

app/views/forms/_form_field_option_fields.erb
<div class="nested-fields">
  <%= f.input :value, label: false, input_html: { size: 50, maxlength: 50 }, wrapper_html: { class: 'form_field_option__input' } %>
  <%= link_to_remove_association 'Remove option', f %>
</div>

app/views/forms/edit.html.erb
<h1>Edit form</h1>
<%= render 'form' %>

app/views/forms/index.html.erb
<% if @forms.any? %>
  <div class="table-container">
    <table>
      <thead>
      <tr>
        <th><%= Form.human_attribute_name(:title) %></th>
        <th><%= Form.human_attribute_name(:description) %></th>
        <th><%= Form.human_attribute_name(:status) %></th>
        <th><%= Form.human_attribute_name(:submissions) %></th>
        <th colspan="3"></th>
      </tr>
      </thead>
      <tbody>
      <% @forms.each do |form| %>
        <tr>
          <td><%= form.title %></td>
          <td><%= form.description %></td>
          <td><%= form.status.humanize %></td>
          <td><%= form.form_submissions_count %></td>
          <td><%= link_to 'Show', form %></td>
          <td><%= edit_form_link(form) %></td>
          <td><%= link_to 'Delete',
                          form_path(form),
                          method: :delete,
                          data:   { confirm: t('activerecord.confirmation.form.destroy') } %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <p>You have not created any form yet</p>
<% end %>
<%= link_to 'New form', new_form_path %>

app/views/forms/new.html.erb
<h1>New form</h1>

<%= render 'form' %>

app/views/forms/show.html.erb
<%= field_set_tag do %>
  <h1><%= @form.title %> <small class="form__status"><%= @form.status.humanize %></small></h1>
  <p><%= @form.description %></p>
  <p><small>* Required</small></p>
<% end %>
<%= field_set_tag do %>
  <% @form_fields.each do |form_field| %>
    <%= form_field.name_required %>
    <%= form_field.description_decorated %>
    <%= form_field.input_mockup %>
  <% end %>
<% end %>
<% if @form.published? %>
  <div class="form__share_link__container">
    <p class="form__share_link__instruction">Copy and send link to surveyees</p>
    <input type="text" value="<%= view_form_url(@form, token: @form.token) %>" size='80' onclick='this.select()' />
  </div>
<% end %>
<div>
  <%= join_elements_by_pipe edit_form_link(@form),
                            publish_form_link(@form),
                            view_form_submissions_link(@form),
                            link_to('Back to forms', forms_path) %>
  <%= link_to 'Delete', form_path(@form),
              method: :delete,
              data:   { confirm: t('activerecord.confirmation.form.destroy') },
              class:  'form__delete_link' %>
</div>

app/views/forms/view.html.erb
<%= field_set_tag do %>
  <h1><%= @form.title %></h1>
  <p><%= @form.description %></p>
  <small>* Required</small>
<% end %>
<%= field_set_tag do %>
  <%= simple_form_for(@form_submission) do |f| %>
    <div class="form-inputs">
      <%= f.error_notification %>

      <%= f.hidden_field :form_id, value: @form_submission.form_id %>
      <%= f.hidden_field :token, value: @form.token %>

      <% @form_entries.each do |form_entry| %>
        <%= f.simple_fields_for :form_entries, form_entry do |form_entry_fields| %>
          <%= form_entry.form_field.decorate.name_required %>
          <%= form_entry.form_field.decorate.description_decorated %>
          <%= form_entry_fields.hidden_field :form_field_id, value: form_entry.form_field_id %>
          <%= form_entry_value_input(form_entry, form_entry_fields) %>
        <% end %>
      <% end %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, 'Submit' %>
      <%= button_tag 'Reset', type: :reset %>
    </div>
  <% end %>
<% end %>